name: CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }} # owner/repo
  # For tags
  VERSION: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: mylorry
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d mylorry"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
    permissions:
      contents: read
      packages: write    # For push to GHCR
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node (for build/test)
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Enable pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Wait for Postgres
        run: |
          sudo apt-get update && sudo apt-get install -y postgresql-client
          until pg_isready -h localhost -p 5432 -U postgres -d mylorry; do
            echo "⏳ waiting for postgres..."
            sleep 2
          done
          echo "✅ Postgres is ready"
        
      - name: Test (unit)
        run: pnpm test
        continue-on-error: true # If you want test failure not to prevent deployment, hold

      - name: Run migrations
        run: pnpm run typeorm:run
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: mylorry
          DB_USER: postgres
          DB_PASSWORD: postgres

      - name: Seed database
        run: pnpm run seed
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: mylorry
          DB_USER: postgres
          DB_PASSWORD: postgres
      
      - name: Test (e2e)
        run: pnpm test:e2e
        continue-on-error: true # If you want test failure not to prevent deployment, hold

      - name: Build Nest
        run: pnpm build

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ env.VERSION }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Upload compose and necessary files to the server
      - name: Upload docker-compose to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: |
            docker-compose.deploy.yml
          target: /home/${{ secrets.SSH_USER }}/mylorry/
          strip_components: 0

      # Update .env on the server (we save the secret somewhere)
      - name: Write .env on server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            cd /home/${{ secrets.SSH_USER }}/mylorry
            cat > .env << 'EOF'
            ${{ secrets.APP_ENV_FILE }}
            EOF

      # Login to GHCR on the server to be able to pull
      - name: Docker login GHCR on server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      # Pull و Up
      - name: Deploy stack
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            cd /home/${{ secrets.SSH_USER }}/mylorry
            # If the original compose file is on the server:
            if [ -f docker-compose.yml ]; then
              COMPOSE_FILE=docker-compose.yml
            else
              # Optionally, name the uploaded file docker-compose.deploy.yml
              COMPOSE_FILE=docker-compose.deploy.yml
            fi
            docker compose -f $COMPOSE_FILE pull
            docker compose -f $COMPOSE_FILE up -d --remove-orphans
            docker system prune -f
